version: '3.4'

services:
  exporter:
    restart: always
    environment:
      - GITHUB_EXPORTER_LOG_LEVEL=debug
      - GITHUB_EXPORTER_LOG_PRETTY=true
      - GITHUB_EXPORTER_WEB_PPROF=true
      - GITHUB_EXPORTER_TOKEN=${GITHUB_EXPORTER_TOKEN}
      - GITHUB_EXPORTER_ORGS=${GITHUB_EXPORTER_ORGS}
      - GITHUB_EXPORTER_REPOS=${GITHUB_EXPORTER_REPOS}
      - GITHUB_EXPORTER_COLLECTOR_ORGS=true
      - GITHUB_EXPORTER_COLLECTOR_REPOS=true
      - GITHUB_EXPORTER_COLLECTOR_BRANCHES=true
      - GITHUB_EXPORTER_COLLECTOR_BILLING=${GITHUB_EXPORTER_COLLECTOR_BILLING:-true}
      - GITHUB_EXPORTER_COLLECTOR_WORKFLOWS=true
      - GITHUB_EXPORTER_COLLECTOR_RUNNERS=${GITHUB_EXPORTER_COLLECTOR_RUNNERS:-true}
      - GITHUB_EXPORTER_APP_ID=1021478
      - GITHUB_EXPORTER_INSTALLATION_ID=55815109
      - GITHUB_EXPORTER_PRIVATE_KEY=file:///kariera-promhippie-exporter.2024-10-11.private-key.pem
    ports:
      - ${GITHUB_EXPORTER_WEB_ADDRESS:-9504}:9504
